/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfaceATM;
import java.sql.*; 
/**
 *
 * @author ridds
 */
public class ChangePin extends javax.swing.JFrame {
    String cardNo;
    /**
     * Creates new form ChangePin
     */
    public ChangePin() {
        initComponents();
        this.cardNo = cardNo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        no4 = new javax.swing.JButton();
        no5 = new javax.swing.JButton();
        no6 = new javax.swing.JButton();
        no7 = new javax.swing.JButton();
        XYZATM = new javax.swing.JLabel();
        no8 = new javax.swing.JButton();
        depositbt = new javax.swing.JButton();
        no9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        no0 = new javax.swing.JButton();
        changepinbt = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        withdrawbt = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        balancebt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        newpinlb = new javax.swing.JLabel();
        tfnewpin = new javax.swing.JTextField();
        exitbt = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        continuebt = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        no1 = new javax.swing.JButton();
        no2 = new javax.swing.JButton();
        no3 = new javax.swing.JButton();
        curpinlb = new javax.swing.JLabel();
        tfcurpin = new javax.swing.JTextField();
        statuscpin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change Pin");

        no4.setText("4");
        no4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no4ActionPerformed(evt);
            }
        });

        no5.setText("5");
        no5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no5ActionPerformed(evt);
            }
        });

        no6.setText("6");
        no6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no6ActionPerformed(evt);
            }
        });

        no7.setText("7");
        no7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no7ActionPerformed(evt);
            }
        });

        XYZATM.setText("Welcome to XYZ ATM");

        no8.setText("8");
        no8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no8ActionPerformed(evt);
            }
        });

        depositbt.setText(">>>");
        depositbt.setEnabled(false);

        no9.setText("9");
        no9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no9ActionPerformed(evt);
            }
        });

        jLabel2.setText("Deposit");

        no0.setText("0");
        no0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no0ActionPerformed(evt);
            }
        });

        changepinbt.setText(">>>");

        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel3.setText("Change Pin");

        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        withdrawbt.setText("<<<");
        withdrawbt.setEnabled(false);

        next.setText("NEXT");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        jLabel4.setText("Withdraw");

        balancebt.setText("<<<");
        balancebt.setEnabled(false);

        jLabel5.setText("Check Balance");

        newpinlb.setText("New Pin");
        newpinlb.setEnabled(false);

        tfnewpin.setEnabled(false);

        exitbt.setText(">>>");
        exitbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtActionPerformed(evt);
            }
        });

        jLabel8.setText("Exit");

        continuebt.setText("<<<");
        continuebt.setEnabled(false);
        continuebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuebtActionPerformed(evt);
            }
        });

        jLabel9.setText("Continue");

        no1.setText("1");
        no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no1ActionPerformed(evt);
            }
        });

        no2.setText("2");
        no2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no2ActionPerformed(evt);
            }
        });

        no3.setText("3");
        no3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no3ActionPerformed(evt);
            }
        });

        curpinlb.setText("Enter Current Pin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(XYZATM)
                .addGap(244, 244, 244))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(depositbt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(changepinbt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exitbt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(statuscpin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(no7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(no8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(no9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(no4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(no5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(no6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(no1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(no2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(no3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(no0, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(next, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 20, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(continuebt))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newpinlb, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(curpinlb, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfcurpin, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addGap(108, 108, 108)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(withdrawbt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfnewpin, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(balancebt))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(XYZATM)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(depositbt)
                            .addComponent(jLabel2)
                            .addComponent(withdrawbt)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changepinbt)
                            .addComponent(jLabel3)
                            .addComponent(balancebt)
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(curpinlb)
                            .addComponent(tfcurpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newpinlb)
                            .addComponent(tfnewpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exitbt)
                        .addComponent(jLabel8)
                        .addComponent(continuebt)
                        .addComponent(jLabel9))
                    .addComponent(statuscpin, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(no0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void no4ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        statuscpin.setText("");
        if (tfcurpin.isEnabled()){
            tfcurpin.setText(tfcurpin.getText() + "4");
        }
        else{
            tfnewpin.setText(tfnewpin.getText() + "4");
        }
    }                                   

    private void no5ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        statuscpin.setText("");
        if (tfcurpin.isEnabled()){
            tfcurpin.setText(tfcurpin.getText() + "5");
        }
        else{
            tfnewpin.setText(tfnewpin.getText() + "5");
        }
    }                                   

    private void no6ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        statuscpin.setText("");
        if (tfcurpin.isEnabled()){
            tfcurpin.setText(tfcurpin.getText() + "6");
        }
        else{
            tfnewpin.setText(tfnewpin.getText() + "6");
        }
    }                                   

    private void no7ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        statuscpin.setText("");
        if (tfcurpin.isEnabled()){
            tfcurpin.setText(tfcurpin.getText() + "7");
        }
        else{
            tfnewpin.setText(tfnewpin.getText() + "7");
        }
    }                                   

    private void no8ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        statuscpin.setText("");
        if (tfcurpin.isEnabled()){
            tfcurpin.setText(tfcurpin.getText() + "8");
        }
        else{
            tfnewpin.setText(tfnewpin.getText() + "8");
        }
    }                                   

    private void no9ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        statuscpin.setText("");
        if (tfcurpin.isEnabled()){
            tfcurpin.setText(tfcurpin.getText() + "9");
        }
        else{
            tfnewpin.setText(tfnewpin.getText() + "9");
        }
    }                                   

    private void no0ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        statuscpin.setText("");
        if (tfcurpin.isEnabled()){
            tfcurpin.setText(tfcurpin.getText() + "0");
        }
        else{
            tfnewpin.setText(tfnewpin.getText() + "0");
        }
    }                                   

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        statuscpin.setText("");
        if (tfnewpin.isEnabled()){
            tfnewpin.setText(null);
        }
        else{
            tfcurpin.setText(null);
        }
    }                                     

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String curpinStr = tfcurpin.getText();
        String pinStr = tfnewpin.getText();
        if (tfnewpin.isEnabled() && pinStr.length() > 0){
            pinStr = pinStr.substring(0, pinStr.length() - 1);
            tfnewpin.setText(pinStr);
        }
        else if (tfcurpin.isEnabled() && curpinStr.length() > 0){
            curpinStr = curpinStr.substring(0, curpinStr.length() - 1);
            tfcurpin.setText(curpinStr);
        }
        else{
            statuscpin.setText("Field Empty");
        }
    }                                      

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        tfcurpin.setEnabled(false);
        curpinlb.setEnabled(false);
        tfnewpin.setEnabled(true);
        newpinlb.setEnabled(true);
        
        continuebt.setEnabled(true);
    }                                    

    private void exitbtActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        System.exit(0);
    }                                      

    private void continuebtActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        PreparedStatement pst = null;
        Connection connector = null;
        int newpin = Integer.parseInt(tfnewpin.getText());
        int curpin = Integer.parseInt(tfcurpin.getText());
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            connector = DriverManager.getConnection("jdbc:mysql://localhost:8111/atm_users?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            pst = connector.prepareStatement("SELECT * FROM `users` WHERE `Card No.` = ?");
            pst.setString(1,cardNo);
            ResultSet rs = pst.executeQuery();
            if (rs.next()){
                int newpinDatabase = rs.getInt(2);
                int curpinDatabase = rs.getInt(3);
                if (newpin == newpinDatabase){
                    curpinDatabase += curpin;
                    //int curpin = Integer.toString(curpinDatabase);
                    //String query = "UPDATE `users` SET `Pin` = " + amtT + " WHERE `Card No.` = " + cardNo;
                    //pst.executeUpdate(query);
                    statuscpin.setText("Amount Deposited");
                }
            }
            pst.close();
            connector.close();
        }
        catch(ClassNotFoundException | SQLException e){ System.out.println("ERROR"+ e); }
    }                                          

    private void no1ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        statuscpin.setText("");
        if (tfcurpin.isEnabled()){
            tfcurpin.setText(tfcurpin.getText() + "1");
        }
        else {
            tfnewpin.setText(tfnewpin.getText() + "1");
        }
    }                                   

    private void no2ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        statuscpin.setText("");
        if (tfcurpin.isEnabled()){
            tfcurpin.setText(tfcurpin.getText() + "2");
        }
        else{
            tfnewpin.setText(tfnewpin.getText() + "2");
        }
    }                                   

    private void no3ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        statuscpin.setText("");
        if (tfcurpin.isEnabled()){
            tfcurpin.setText(tfcurpin.getText() + "3");
        }
        else{
            tfnewpin.setText(tfnewpin.getText() + "3");
        }
    }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel XYZATM;
    private javax.swing.JButton balancebt;
    private javax.swing.JButton cancel;
    private javax.swing.JButton changepinbt;
    private javax.swing.JButton clear;
    private javax.swing.JButton continuebt;
    private javax.swing.JLabel curpinlb;
    private javax.swing.JButton depositbt;
    private javax.swing.JButton exitbt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel newpinlb;
    private javax.swing.JButton next;
    private javax.swing.JButton no0;
    private javax.swing.JButton no1;
    private javax.swing.JButton no2;
    private javax.swing.JButton no3;
    private javax.swing.JButton no4;
    private javax.swing.JButton no5;
    private javax.swing.JButton no6;
    private javax.swing.JButton no7;
    private javax.swing.JButton no8;
    private javax.swing.JButton no9;
    private javax.swing.JLabel statuscpin;
    private javax.swing.JTextField tfcurpin;
    private javax.swing.JTextField tfnewpin;
    private javax.swing.JButton withdrawbt;
    // End of variables declaration                   
}
